// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Response struct {
	Message string `json:"message"`
}

type Shipment struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Origin       string `json:"origin"`
	Destination  string `json:"destination"`
	DeliveryDate string `json:"deliveryDate"`
	CreatedAt    string `json:"createdAt"`
	UpdatedAt    string `json:"updatedAt"`
	Truck        *Truck `json:"truck"`
	Page         int    `json:"page"`
	First        int    `json:"first"`
}

type Truck struct {
	ID        string `json:"id"`
	PlateNo   string `json:"plateNo"`
	IsDeleted *bool  `json:"isDeleted"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	Page      int    `json:"page"`
	First     int    `json:"first"`
}
